[project]
name = "idhagn_bot"
description = "Simple chatbot for Tencent QQ."
authors = [
  {name = "su226", email = "thesu226@outlook.com"},
]
license = {text = "MIT"}
requires-python = ">=3.10,<4.0"
dependencies = [
  "nonebot2[aiohttp]<3.0.0.0,>=2.0.0-beta.3",
  "nonebot-adapter-onebot<3.0.0.0,>=2.0.0-beta.1",
  "nonebot-plugin-apscheduler<1.0.0,>=0.1.2",
  "PyYAML<7.0,>=6.0",
  "Pillow<10.0.0,>=9.1.0",
  "numpy<2.0.0,>=1.22.3",
  "pyppeteer<2.0.0,>=1.0.2",
  "pycairo<2.0.0,>=1.21.0",
  "PyGObject<4.0.0,>=3.42.1",
  "psutil<6.0.0,>=5.9.0",
  "jieba<1.0.0,>=0.42.1",
]

[project.optional-dependencies]
all = ["libzim<2.0.0,>=1.0.0", "mctools<2.0.0,>=1.1.2"]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"

[tool.pdm]
includes = []

[tool.pdm.dev-dependencies]
dev = [
  "pylama[eradicate,isort,pycodestyle,pyflakes]<9.0.0,>=8.3.8",
]

[tool.pdm.scripts]
start = "python bot.py"

[tool.isort]
multi_line_output = 4
line_length = 100
indent = "  "

[tool.pyright]
typeCheckingMode = "basic"
strict = ["plugins/liferestart/game"]
