[project]
name = "idhagn_bot"
description = "Simple chatbot for Tencent QQ."
authors = [
  {name = "su226", email = "thesu226@outlook.com"},
]
readme = "README.md"
keywords = ["nonebot", "nonebot2", "bot", "qq", "chatbot", "qqbot"]
license = {text = "MIT"}
requires-python = ">=3.10,<4.0"
dependencies = [
  "nonebot2[aiohttp]<3.0.0.0,>=2.0.0-beta.3",
  "nonebot-adapter-onebot<3.0.0.0,>=2.0.0-beta.1",
  "nonebot-plugin-apscheduler<1.0.0,>=0.1.2",
  "PyYAML<7.0,>=6.0",
  "Pillow<10.0.0,>=9.1.0",
  "pycairo<2.0.0,>=1.21.0",
  "PyGObject<4.0.0,>=3.42.1",
]

[project.optional-dependencies]
jieba = ["jieba<1.0.0,>=0.42.1"]
libzim = ["libzim<2.0.0,>=1.0.0"]
mctools = ["mctools<2.0.0,>=1.1.2"]
psutil = ["psutil<6.0.0,>=5.9.0"]
pyppeteer = ["pyppeteer<2.0.0,>=1.0.2"]
opencv = ["opencv-python-headless>=4.6.0.66"]

[project.urls]
Homepage = "https://idhagnbot.su226.tk"
Repository = "https://github.com/su226/IdhagnBot"
Documentation = "https://idhagnbot.su226.tk"

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"

[tool.pdm]
includes = []

[tool.pdm.dev-dependencies]
dev = [
  "pylama[eradicate]<9.0.0,>=8.3.8",
  "types-Pillow>=9.2.1",  # Pyright自带那个有点老……
  "numpy>=1.23.2",
]

[tool.pdm.scripts]
start = "python bot.py"

[tool.isort]
multi_line_output = 4
line_length = 100
indent = "  "

[tool.pyright]
typeCheckingMode = "basic"
strict = ["plugins/liferestart/game"]
