[project]
name = "idhagnbot"
description = "Simple chatbot for Tencent QQ."
authors = [
  {name = "su226", email = "thesu226@outlook.com"},
]
readme = "README.md"
keywords = ["nonebot", "nonebot2", "bot", "qq", "chatbot", "qqbot"]
license = {text = "MIT"}
requires-python = ">=3.8,<4.0"
dependencies = [
  "nonebot2[aiohttp]<3,>=2.0.0-beta.3",
  "nonebot-adapter-onebot<3,>=2.0.0-beta.1",
  "nonebot-plugin-apscheduler<2,>=0.1.2",
  "PyYAML<7,>=6.0",
  "Pillow>=10.0.0",
  "pycairo<2,>=1.21.0",
  "PyGObject<4,>=3.42.1", # PDM 无法安装 3.44.0 和 3.44.1
]

[project.optional-dependencies]
jieba = ["jieba<2,>=0.42.1"]
libzim = ["libzim<3,>=2.0.0; python_version < '3.12'"] # 维基百科也需要 pyppeteer
mctools = ["mctools<2,>=1.1.2"]
psutil = ["psutil<6,>=5.9.0"]
opencv = ["opencv-python-headless<5,>=4.6.0.66"]
sql = ["sqlmodel<2,>=0.0.8", "aiosqlite<2,>=0.17.0"]
wordcloud = ["wordcloud<2,>=1.9.2", "emoji>=2.8.0"] # 词云也需要 sql 和 jieba
grpc = ["protobuf<5,>=4.21.6", "grpcio<2,>=1.49.1"]
playwright = ["playwright<2,>=1.27.1"]

[project.urls]
Homepage = "https://idhagnbot.su226.eu.org"
Repository = "https://github.com/su226/IdhagnBot"
Documentation = "https://idhagnbot.su226.eu.org"

[build-system]
requires = ["pdm-pep517<2,>=0.12.0"]
build-backend = "pdm.pep517.api"

[tool.pdm]
includes = []

[tool.pdm.dev-dependencies]
lint = [
  "pylama[eradicate,toml]<9,>=8.4.1",
  "isort<6,>=5.10.1",
]
dev = [
  "grpc-stubs<2,>=1.53.0.2",
  "mypy-protobuf<4,>=3.4.0",
  "grpcio-tools<2,>=1.54.2",
  "opencv-stubs<2,>=0.0.8",
]

[tool.pdm.scripts]
start = "python bot.py"
bilibili_activity_compile = "tools/bilibili_activity_compile.sh"

[tool.isort]
multi_line_output = 5
combine_as_imports = true
line_length = 99
indent = "  "

[tool.pyright]
typeCheckingMode = "strict"
strict = ["plugins/liferestart/game"]
ignore = ["util/api_common/*/protos", "archived"]
pythonVersion = "3.8"
reportMissingTypeStubs = false
reportConstantRedefinition = false
reportPrivateUsage = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false

[tool.pylama]
linters = "eradicate,pycodestyle,pyflakes,isort"
skip = ".venv*/*,util/api_common/*/protos/*"
async = true

[tool.pylama.linter.pycodestyle]
ignore = "E128,E302,E305,E402,E741,E704,W503"
indent_size = 2
max_line_length = 99
